module.exports = {
	content: [
		'./components/**/*.{jsx,tsx}',
		'./features/**/*.{jsx,tsx}',
		'./layouts/**/*.{jsx,tsx}',
		'./pages/**/*.{jsx,tsx}',
		'./page-components/**/*.{jsx,tsx}',
	],
	theme: {
		screens: {
			xs: '536px',
			sm: '640px',
			md: '768px',
			lg: '1024px',
			xl: '1280px',
			'2xl': '1536px',
		},
		container: {
			screens: {
				sm: '600px',
				md: '728px',
				lg: '984px',
				xl: '1240px',
				'2xl': '1400px',
			},
			padding: {
				DEFAULT: '1rem',
				sm: '1.5rem',
			},
		},
		fontFamily: {},
		fontSize: {
			'display-2xl': ['var(--fs-display-2xl)', 'var(--lh-display-2xl)'],
			'display-xl': ['var(--fs-display-xl)', 'var(--lh-display-xl)'],
			'display-lg': ['var(--fs-display-lg)', 'var(--lh-display-lg)'],
			'display-md': ['var(--fs-display-md)', 'var(--lh-display-md)'],
			'display-sm': ['var(--fs-display-sm)', 'var(--lh-display-sm)'],
			'display-xs': ['var(--fs-display-xs)', 'var(--lh-display-xs)'],
			xl: ['var(--fs-text-xl)', 'var(--lh-text-xl)'],
			lg: ['var(--fs-text-lg)', 'var(--lh-text-lg)'],
			md: ['var(--fs-text-md)', 'var(--lh-text-md)'],
			sm: ['var(--fs-text-sm)', 'var(--lh-text-sm)'],
			xs: ['var(--fs-text-xs)', 'var(--lh-text-xs)'],
			'2xs': ['var(--fs-text-2xs)', 'var(--lh-text-2xs)'],
		},
		fontWeight: {
			light: 'var(--fw-light)',
			regular: 'var(--fw-regular)',
			medium: 'var(--fw-medium)',
			semibold: 'var(--fw-semibold)',
			bold: 'var(--fw-bold)',
			extrabold: 'var(--fw-extrabold)',
			black: 'var(--fw-black)',
		},
		extend: {
			boxShadow: {
				xs: 'var(--shadow-xs)',
				sm: 'var(--shadow-sm)',
				md: 'var(--shadow-md)',
				lg: 'var(--shadow-lg)',
				xl: 'var(--shadow-xl)',
				'2xl': 'var(--shadow-2xl)',
				'3xl': 'var(--shadow-3xl)',
			},
			colors: {
				white: 'var(--white)',
				black: 'var(--black)',
				primary: {
					50: 'var(--primary-50)',
					100: 'var(--primary-100)',
					200: 'var(--primary-200)',
					300: 'var(--primary-300)',
					400: 'var(--primary-400)',
					500: 'var(--primary-500)',
					600: 'var(--primary-600)',
					700: 'var(--primary-700)',
					800: 'var(--primary-800)',
					900: 'var(--primary-900)',
				},
				gray: {
					50: 'var(--gray-50)',
					100: 'var(--gray-100)',
					200: 'var(--gray-200)',
					300: 'var(--gray-300)',
					400: 'var(--gray-400)',
					500: 'var(--gray-500)',
					600: 'var(--gray-600)',
					700: 'var(--gray-700)',
					800: 'var(--gray-800)',
					900: 'var(--gray-900)',
				},
				blue: {
					50: 'var(--blue-50)',
					100: 'var(--blue-100)',
					200: 'var(--blue-200)',
					300: 'var(--blue-300)',
					400: 'var(--blue-400)',
					500: 'var(--blue-500)',
					600: 'var(--blue-600)',
					700: 'var(--blue-700)',
					800: 'var(--blue-800)',
					900: 'var(--blue-900)',
				},
				red: {
					50: 'var(--red-50)',
					100: 'var(--red-100)',
					200: 'var(--red-200)',
					300: 'var(--red-300)',
					400: 'var(--red-400)',
					500: 'var(--red-500)',
					600: 'var(--red-600)',
					700: 'var(--red-700)',
					800: 'var(--red-800)',
					900: 'var(--red-900)',
				},
				yellow: {
					50: 'var(--yellow-50)',
					100: 'var(--yellow-100)',
					200: 'var(--yellow-200)',
					300: 'var(--yellow-300)',
					400: 'var(--yellow-400)',
					500: 'var(--yellow-500)',
					600: 'var(--yellow-600)',
					700: 'var(--yellow-700)',
					800: 'var(--yellow-800)',
					900: 'var(--yellow-900)',
				},
				green: {
					50: 'var(--green-50)',
					100: 'var(--green-100)',
					200: 'var(--green-200)',
					300: 'var(--green-300)',
					400: 'var(--green-400)',
					500: 'var(--green-500)',
					600: 'var(--green-600)',
					700: 'var(--green-700)',
					800: 'var(--green-800)',
					900: 'var(--green-900)',
				},
			},
			width: {},
			height: {},
			spacing: {},
			zIndex: {
				negative: 'var(--z-negative)',
				elevate: 'var(--z-elevate)',
				sticky: 'var(--z-sticky)',
				drawer: 'var(--z-drawer)',
				dropdown: 'var(--z-dropdown)',
				modal: 'var(--z-modal)',
				popover: 'var(--z-popover)',
				maximum: 'var(--z-maximum)',
			},
		},
		animation: {},
		keyframes: {},
	},
	plugins: [
		function ({ addVariant }) {
			addVariant('child', '& > *')
			addVariant('child-hover', '& > *:hover')
			addVariant('descendant', '& *')
			addVariant('descendant-hover', '& *:hover')
		},
	],
}
